# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3003286a6b7a14326e3e4fb8e023ab83cb1c3c66ef749b3d76b7ebe8bf0219df95d11568969f1e4a785f77782035603000c2206dcfe63cc45ae53201a7407804

test:
  secret_key_base: 2f4814a03b77d75229ee0b6132d136033000d69cbca05c72073288b15b685d8a9cf740f8cec2e8af85fec73472d494a773d9df30cdc8303b695f2399733722aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
